SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;

ALTER TABLE `alerts` CHANGE `UDSAttributes` `UDSAttributes` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL;

UPDATE `settings` SET `value` = '1.9' WHERE `settings`.`code` = 'DATABASE VERSION';

COMMIT;